name: FetchANGLE

on: workflow_dispatch

jobs:
    fetch:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repo
              uses: actions/checkout@v4
            - name: Fetch Angle
              run: bash ./downloadAngle.sh
            - name: Upload
              uses: actions/upload-artifact@v4
              with:
                name: ANGLE
                path: |
                    windows32/
                    windows64/
                    macosx64/
                    macosarm64/
                    