name: FetchANGLE

on: workflow_dispatch

jobs:
    fetch:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Clone Repo
              uses: actions/checkout@v4
            - name: Fetch Angle
              run: bash ./downloadAngle.sh
            - name: Upload Release
              uses: softprops/action-gh-release@v2
              with:
                files: angle.zip
                tag_name: angle
                body_path: Info.md
